language: c
compiler: gcc
dist: xenial
notifications:
  email: false

before_install:
    - git submodule init
    - git submodule update --recursive

script:
    - export CC=gcc-5
    - mkdir build
    - cd build 
    - cmake -DBUILD_DAP_CORE_SERVER_TESTS=ON ../
    - make
    - ctest --verbose

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - libev-dev

